# Site settings
# Site settings
title: Carro Inteligente
email: fernando.passe@ufv.br
description: > # this means to ignore newlines until "baseurl:"
  Este projeto visa contruir uma das aplicações possíveis da visão computacional, que consiste
  em aplicar estes conceitos em um veículo afim de torná-lo autônomo, ou seja capaz de
  avaliar as condições do meio e se locomover sem que haja interferência. O protótipo a ser
  desenvolvido utilizará hardware de baixo custo, para isso utilizaremos Arduino, Raspberry
  Pi, câmera e alguns sensores
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://fernandopasse.website" # the base hostname & protocol for your site
twitter_username: fernandopasse
github_username:  fernandopasse
google_play:
google_plus_com:  # Community link
google_plus_per:  #Personal link
facebook_app_id: 12345

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Pontos de controle
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com
  option3:
    name: Cool Option 3
    link: www.myawesomelink.com

disqus: true
disqus_shortname: 'carrointeligente'

# Build settings
markdown: kramdown
